{{- $services := dict
    "adService" .Values.adService
    "cartService" .Values.cartService
    "checkoutService" .Values.checkoutService
    "currencyService" .Values.currencyService
    "emailService" .Values.emailService
    "frontend" .Values.frontend
    "loadGenerator" .Values.loadGenerator
    "paymentService" .Values.paymentService
    "productCatalogService" .Values.productCatalogService
    "recommendationService" .Values.recommendationService
    "shippingService" .Values.shippingService
-}}

{{- range $name, $svc := $services }}
{{- if and $svc.create (hasKey $svc "hpa") (and $svc.hpa.enabled (hasKey $svc.hpa "cpu")) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $svc.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $svc.name }}
  minReplicas: {{ default 1 $svc.hpa.minReplicas }}
  maxReplicas: {{ default 5 $svc.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ default 60 $svc.hpa.cpu.targetAverageUtilization }}
---
{{- end }}
{{- end }}
