images:
  repository: pathfindersh/hipster-app
  tag: ""
serviceAccounts:
  create: true
  annotations: {}
  annotationsOnlyForCartservice: false
networkPolicies:
  create: false
sidecars:
  create: false
authorizationPolicies:
  create: false
opentelemetryCollector:
  create: false
  name: opentelemetrycollector
  projectId: "PROJECT_ID"
googleCloudOperations:
  profiler: false
  tracing: false
  metrics: false
seccompProfile:
  enable: false
  type: RuntimeDefault
securityContext:
  enable: true
imagePullSecret:
  dockerconfigjson: "eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJwYXRoZmluZGVyc2giLCJwYXNzd29yZCI6IlBhdGhARG9ja2VyIzEyMyIsImVtYWlsIjoiZGV2c2h1MkBnbWFpbC5jb20iLCJhdXRoIjoiY0dGMGFHWnBibVJsY25Ob09sQmhkR2hBUkc5amEyVnlJekV5TXc9PSJ9fX0="
adService:
  create: true
  name: adservice
  image:
    repository: docker.io/pathfindersh/hipster-app
    tag: adservice-v0.8.0
  resources:
    requests:
      cpu: 200m
      memory: 180Mi
    limits:
      cpu: 300m
      memory: 300Mi
cartService:
  create: true
  name: cartservice
  image:
    repository: docker.io/pathfindersh/hipster-app
    tag: cartservice-v0.8.0
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
checkoutService:
  create: true
  name: checkoutservice
  image:
    repository: docker.io/pathfindersh/hipster-app
    tag: checkoutservice-v0.8.0
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
currencyService:
  create: true
  name: currencyservice
  image:
    repository: docker.io/pathfindersh/hipster-app
    tag: currencyservice-v0.8.0
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
emailService:
  create: trueͥ旡ɍ
  name: emailservice
  image:
    repository: docker.io/pathfindersh/hipster-app
    tag: emailservice-v0.8.0
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
frontend:
  create: true
  name: frontend
  image:
    repository: docker.io/pathfindersh/hipster-app
    tag: frontend-v0.8.0
  externalService: true
  cymbalBranding: false
  platform: local
  singleSharedSession: false
  virtualService:
    create: false
    hosts:
      - "*"
    gateway:
      name: asm-ingressgateway
      namespace: asm-ingress
      labelKey: asm
      labelValue: ingressgateway
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
loadGenerator:
  create: true
  name: loadgenerator
  image:
    repository: docker.io/pathfindersh/hipster-app
    tag: loadgenerator-v0.8.0
  checkFrontendInitContainer: true
  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
paymentService:
  create: true
  name: paymentservice
  image:
    repository: docker.io/pathfindersh/hipster-app
    tag: paymentservice-v0.8.0
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
productCatalogService:
  create: true
  name: productcatalogservice
  image:
    repository: docker.io/pathfindersh/hipster-app
    tag: productcatalogservice-v0.8.0
  extraLatency: ""
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
recommendationService:
  create: true
  name: recommendationservice
  image:
    repository: docker.io/pathfindersh/hipster-app
    tag: recommendationservice-v0.8.0
  resources:
    requests:
      cpu: 100m
      memory: 220Mi
    limits:
      cpu: 200m
      memory: 450Mi
shippingService:
  create: true
  name: shippingservice
  image:
    repository: docker.io/pathfindersh/hipster-app
    tag: shippingservice-v0.8.0
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
cartDatabase:
  type: redis
  connectionString: "redis-cart:6379"
  inClusterRedis:
    create: true
    name: redis-cart
    publicRepository: true
  externalRedisTlsOrigination:
    enable: false
    name: exernal-redis-tls-origination
    endpointAddress: ""
    endpointPort: ""
    certificate: ""
shoppingAssistantService:
  create: false
  name: shoppingassistantservice
AdserviceService:
  image:
    tag: 0.8.1
