# hipster-argo-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipster-shop
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/pathfindersh/microservices-demo
    targetRevision: HEAD
    path: kubernetes-manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: hipster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

