# hipster-argo-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipster-shop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pathfindersh/microservices-demo
    targetRevision: HEAD
    path: hipster/helm-chart           # ✅ Switch from kustomize path to Helm chart
    helm:
      valueFiles:
        - values.yaml          # ✅ Default values
      parameters:
        - name: namespace
          value: hipster       # Optional override if the chart uses .Values.namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: hipster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

