name: Build & Push Docker images ## Building image and pushing in docker

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'New Image Tag (e.g. adservice-v0.8.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: pathfindersh
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t pathfindersh/hipster-app:${{ github.event.inputs.image_tag }} .hipster/src/adservice
          docker push pathfindersh/hipster-app:${{ github.event.inputs.image_tag }}
