name: Build & Push All Services

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: 'Image Tag (e.g. v0.8.0)'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - adservice
          - cartservice
          - checkoutservice
          - currencyservice
          - emailservice
          - frontend
          - loadgenerator
          - paymentservice
          - productcatalogservice
          - recommendationservice
          - shippingservice
          - shoppingassistantservice

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: pathfindersh
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ${{ matrix.service }}
        run: |
          docker build -t pathfindersh/hipster-app:${{ matrix.service }}-${{ github.event.inputs.IMAGE_TAG }} ./hipster/src/${{ matrix.service }}
          docker push pathfindersh/hipster-app:${{ matrix.service }}-${{ github.event.inputs.IMAGE_TAG }}