# .github/workflows/gitleaks.yml

name: Gitleaks Secret Scan

on:
  workflow_call:
    secrets:
      gh_pat:
        required: true

jobs:
  gitleaks-scan:
    name: Run Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.gh_pat }}

      - name: Download Gitleaks Binary
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks (fail if secrets found)
        run: |
          gitleaks detect \
            --source . \
            --report-format json \
            --report-path gitleaks-report.json \
            --no-git

      - name: Print Gitleaks Findings
        if: always()
        run: |
          echo "📄 Gitleaks Report Contents:"
          cat gitleaks-report.json || echo "⚠️ Report file not found"

      - name: Upload Gitleaks Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json