name: CI/CD Orchestration Pipeline with reusable Workflows

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service name (e.g. adservice)'
        required: true
      image_version:
        description: 'Image tag (e.g. v0.8.0)'
        required: true
      skip_build:
        description: 'Skip Docker Build & push? (true/false)'
        required: false
        default: 'false'
      skip_deploy:
        description: 'Skip ArgoCD deploy? (true/false)'
        required: false
        default: 'false'

jobs:

  polaris_scan:
    uses: ./.github/workflows/polaris.yml
    secrets:
      gh_pat: ${{ secrets.GH_PAT }}

  unit_tests:
    needs: polaris_scan
    uses: ./.github/workflows/unit-test.yml
    with:
      service: ${{ github.event.inputs.service }}

  build_and_push:
    if: ${{ inputs.skip_build != 'true' }}
    needs: unit_tests
    uses: ./.github/workflows/docker-build.yml
    with:
      image_version: ${{ github.event.inputs.image_version }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  argocd_deploy_without_build:
    if: ${{ inputs.skip_build == 'true' && inputs.skip_deploy != 'true' }}
    uses: ./.github/workflows/argo-update.yml
    with:
      service: ${{ inputs.service }}
      image_tag: ${{ inputs.image_version }}
    secrets:
      gh_pat: ${{ secrets.GH_PAT }}
