name: CI/CD Orchestration Pipeline with reusable Workflows .

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service name (e.g. adservice)'
        required: true
      image_version:
        description: 'Image tag (e.g. v0.8.0)'
        required: true

jobs:

  gitleaks_scan:
    uses: ./.github/workflows/gitleaks.yml
    secrets:
      gh_pat: ${{ secrets.GH_PAT }}
  
  polaris_scan:
    needs: gitleaks_scan
    uses: ./.github/workflows/polaris.yml
    secrets:
      gh_pat: ${{ secrets.GH_PAT }}

  unit_tests:
    needs: polaris_scan
    uses: ./.github/workflows/unit-test.yml
    with:
      service: ${{ github.event.inputs.service }}

  build_and_push:
    if: ${{ always() }}
    needs: unit_tests
    uses: ./.github/workflows/docker-build.yml
    with:
      image_version: ${{ github.event.inputs.image_version }}
    secrets:
      DOCKER_USERNAME: pathfindersh
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  trivy_scan:
    if: ${{ always() }}
    needs: build_and_push
    uses: ./.github/workflows/trivy.yml
    with:
      image_version: ${{ github.event.inputs.image_version }}
    secrets:
      DOCKER_USERNAME: pathfindersh
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


  argocd_deploy:
    if: ${{ always() }}
    needs: trivy_scan
    uses: ./.github/workflows/argo-update.yml
    with:
      service: ${{ github.event.inputs.service }}
      image_tag: ${{ github.event.inputs.image_version }}
    secrets:
      gh_pat: ${{ secrets.GH_PAT }}