name: Syft + Grype OSS Dependency Scan

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  syft_grype_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Set image reference
        id: prep
        run: echo "IMAGE=${{ inputs.image_name }}:${{ inputs.image_tag }}" >> $GITHUB_ENV

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM using Syft
        run: |
          syft $IMAGE -o json > sbom-${{ inputs.image_tag }}.json

      - name: Scan image using Grype
        run: |
          grype $IMAGE -o json > grype-report-${{ inputs.image_tag }}.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ inputs.image_tag }}
          path: sbom-${{ inputs.image_tag }}.json

      - name: Upload Grype scan artifact
        uses: actions/upload-artifact@v4
        with:
          name: grype-report-${{ inputs.image_tag }}
          path: grype-report-${{ inputs.image_tag }}.json
