name: Trivy Image Vulnerability Scan

on:
  workflow_call:
    inputs:
      image_version:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  trivy-scan:
    strategy:
      matrix:
        service:
          - adservice
          - cartservice
          - checkoutservice
          - currencyservice
          - emailservice
          - frontend
          - loadgenerator
          - paymentservice
          - productcatalogservice
          - recommendationservice
          - shippingservice

    runs-on: ubuntu-latest
    env:
      IMAGE: pathfindersh/hipster-app:${{ matrix.service }}-${{ inputs.image_version }}

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: pathfindersh
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Trivy Scan (table)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{ env.IMAGE }}
          format: table
          exit-code: 0
          ignore-unfixed: true

      - name: Save Trivy JSON Report
        run: |
          trivy image --format json --output trivy-${{ matrix.service }}.json $IMAGE

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-${{ matrix.service }}
          path: trivy-${{ matrix.service }}.json
